const StudentData = [
  {
    student: 'Evelyn',
    opdracht: 'W1D1-1',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Evelyn',
    opdracht: 'W1D2-1',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Evelyn',
    opdracht: 'W1D2-2',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Evelyn',
    opdracht: 'W1D2-3',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Evelyn',
    opdracht: 'W1D2-4',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Evelyn',
    opdracht: 'W1D2-5',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Evelyn',
    opdracht: 'W1D3-1',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Evelyn',
    opdracht: 'W1D3-2',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Evelyn',
    opdracht: 'W1D3-4',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Evelyn',
    opdracht: 'W1D3-5',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Evelyn',
    opdracht: 'W1D3',
    moeilijkheid: 5,
    plezier: 5,
  },
  {
    student: 'Evelyn',
    opdracht: 'W1D4-1',
    moeilijkheid: 4,
    plezier: 5,
  },
  {
    student: 'Evelyn',
    opdracht: 'W1D4',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Evelyn',
    opdracht: 'W1D5',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Evelyn',
    opdracht: 'W2D1-1',
    moeilijkheid: 1,
    plezier: 5,
  },
  {
    student: 'Evelyn',
    opdracht: 'W2D1-2',
    moeilijkheid: 2,
    plezier: 5,
  },
  {
    student: 'Evelyn',
    opdracht: 'W2D2-1',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Evelyn',
    opdracht: 'W2D2-2',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Evelyn',
    opdracht: 'W2D2-3',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Evelyn',
    opdracht: 'W2D3-1',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Evelyn',
    opdracht: 'W2D3-2',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Evelyn',
    opdracht: 'W2D3-3',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Evelyn',
    opdracht: 'W2D4-1',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Evelyn',
    opdracht: 'W2D4-2',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Evelyn',
    opdracht: 'W2D4-3',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Evelyn',
    opdracht: 'W2D5',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Evelyn',
    opdracht: 'W3D1-1',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Evelyn',
    opdracht: 'W3D1-2',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Evelyn',
    opdracht: 'W3D1-3',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Evelyn',
    opdracht: 'W3D1-4',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Evelyn',
    opdracht: 'W3D2-1',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Evelyn',
    opdracht: 'W3D2-2',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Evelyn',
    opdracht: 'W3D2-3',
    moeilijkheid: 3,
    plezier: 5,
  },
  {
    student: 'Evelyn',
    opdracht: 'W3D3-1',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Evelyn',
    opdracht: 'W3D3-2',
    moeilijkheid: 4,
    plezier: 5,
  },
  {
    student: 'Evelyn',
    opdracht: 'W3D3-3',
    moeilijkheid: 3,
    plezier: 5,
  },
  {
    student: 'Evelyn',
    opdracht: 'W3D3-4',
    moeilijkheid: 4,
    plezier: 5,
  },
  {
    student: 'Evelyn',
    opdracht: 'W3D4-1',
    moeilijkheid: 5,
    plezier: 5,
  },
  {
    student: 'Evelyn',
    opdracht: 'W3D4-2',
    moeilijkheid: 1,
    plezier: 5,
  },
  {
    student: 'Evelyn',
    opdracht: 'W3D5',
    moeilijkheid: 2,
    plezier: 5,
  },
  {
    student: 'Evelyn',
    opdracht: 'W4D2-1',
    moeilijkheid: 1,
    plezier: 5,
  },
  {
    student: 'Evelyn',
    opdracht: 'W4D2-2',
    moeilijkheid: 1,
    plezier: 5,
  },
  {
    student: 'Evelyn',
    opdracht: 'W4D2-3',
    moeilijkheid: 1,
    plezier: 5,
  },
  {
    student: 'Evelyn',
    opdracht: 'W4D2-4',
    moeilijkheid: 1,
    plezier: 5,
  },
  {
    student: 'Evelyn',
    opdracht: 'W4D3-1',
    moeilijkheid: 1,
    plezier: 5,
  },
  {
    student: 'Evelyn',
    opdracht: 'W4D3-2',
    moeilijkheid: 1,
    plezier: 5,
  },
  {
    student: 'Evelyn',
    opdracht: 'W4D3-3',
    moeilijkheid: 1,
    plezier: 5,
  },
  {
    student: 'Evelyn',
    opdracht: 'W4D3-4',
    moeilijkheid: 1,
    plezier: 5,
  },
  {
    student: 'Evelyn',
    opdracht: 'W4D3-5',
    moeilijkheid: 1,
    plezier: 5,
  },
  {
    student: 'Evelyn',
    opdracht: 'W4D3',
    moeilijkheid: 1,
    plezier: 5,
  },
  {
    student: 'Evelyn',
    opdracht: 'W5D4-1',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Evelyn',
    opdracht: 'W5D5',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Evelyn',
    opdracht: 'W6D1-1',
    moeilijkheid: 5,
    plezier: 5,
  },
  {
    student: 'Evelyn',
    opdracht: 'W6D2-1',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Evelyn',
    opdracht: 'W6D2',
    moeilijkheid: 5,
    plezier: 5,
  },
  {
    student: 'Aranka',
    opdracht: 'W4D2',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Aranka',
    opdracht: 'W1D1-1',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Aranka',
    opdracht: 'W1D2-1',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Aranka',
    opdracht: 'W1D2-2',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Aranka',
    opdracht: 'W1D2-3',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Aranka',
    opdracht: 'W1D2-4',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Aranka',
    opdracht: 'W1D2-5',
    moeilijkheid: 4,
    plezier: 2,
  },
  {
    student: 'Aranka',
    opdracht: 'W1D3-1',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Aranka',
    opdracht: 'W1D3-2',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Aranka',
    opdracht: 'W1D3-4',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Aranka',
    opdracht: 'W1D3-5',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Aranka',
    opdracht: 'W1D3',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Aranka',
    opdracht: 'W1D4-1',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Aranka',
    opdracht: 'W1D4',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Aranka',
    opdracht: 'W1D5',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Aranka',
    opdracht: 'W2D1-1',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Aranka',
    opdracht: 'W2D1-2',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Aranka',
    opdracht: 'W2D2-1',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Aranka',
    opdracht: 'W2D2-2',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Aranka',
    opdracht: 'W2D2-3',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Aranka',
    opdracht: 'W2D3-1',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Aranka',
    opdracht: 'W2D3-2',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Aranka',
    opdracht: 'W2D3-3',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Aranka',
    opdracht: 'W2D4-1',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Aranka',
    opdracht: 'W2D4-2',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Aranka',
    opdracht: 'W2D4-3',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Aranka',
    opdracht: 'W2D5',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Aranka',
    opdracht: 'W3D1-1',
    moeilijkheid: 4,
    plezier: 2,
  },
  {
    student: 'Aranka',
    opdracht: 'W3D1-2',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Aranka',
    opdracht: 'W3D1-3',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Aranka',
    opdracht: 'W3D1-4',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Aranka',
    opdracht: 'W3D2-1',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Aranka',
    opdracht: 'W3D2-2',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Aranka',
    opdracht: 'W3D2-3',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Aranka',
    opdracht: 'W3D3-1',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Aranka',
    opdracht: 'W3D3-2',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Aranka',
    opdracht: 'W3D3-3',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Aranka',
    opdracht: 'W3D3-4',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Aranka',
    opdracht: 'W3D4-1',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Aranka',
    opdracht: 'W3D4-2',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Aranka',
    opdracht: 'W3D5',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Aranka',
    opdracht: 'W4D2-1',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Evelyn',
    opdracht: 'W4D2',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Aranka',
    opdracht: 'W4D2-2',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Aranka',
    opdracht: 'W4D2-3',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Aranka',
    opdracht: 'W4D2-4',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Aranka',
    opdracht: 'W4D3-1',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Aranka',
    opdracht: 'W4D3-2',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Aranka',
    opdracht: 'W4D3-3',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Aranka',
    opdracht: 'W4D3-4',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Aranka',
    opdracht: 'W4D3-5',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Aranka',
    opdracht: 'W4D3',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Aranka',
    opdracht: 'W5D4-1',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Aranka',
    opdracht: 'W5D5',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Aranka',
    opdracht: 'W6D1-1',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Aranka',
    opdracht: 'W6D2-1',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Aranka',
    opdracht: 'W6D2',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Floris',
    opdracht: 'W4D2',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Floris',
    opdracht: 'W1D1-1',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Floris',
    opdracht: 'W1D2-1',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Floris',
    opdracht: 'W1D2-2',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Floris',
    opdracht: 'W1D2-3',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Floris',
    opdracht: 'W1D2-4',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Floris',
    opdracht: 'W1D2-5',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Floris',
    opdracht: 'W1D3-1',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Floris',
    opdracht: 'W1D3-2',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Floris',
    opdracht: 'W1D3-4',
    moeilijkheid: 4,
    plezier: 2,
  },
  {
    student: 'Floris',
    opdracht: 'W1D3-5',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Floris',
    opdracht: 'W1D3',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Floris',
    opdracht: 'W1D4-1',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Floris',
    opdracht: 'W1D4',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Floris',
    opdracht: 'W1D5',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Floris',
    opdracht: 'W2D1-1',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Floris',
    opdracht: 'W2D1-2',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Floris',
    opdracht: 'W2D2-1',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Floris',
    opdracht: 'W2D2-2',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Floris',
    opdracht: 'W2D2-3',
    moeilijkheid: 4,
    plezier: 2,
  },
  {
    student: 'Floris',
    opdracht: 'W2D3-1',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Floris',
    opdracht: 'W2D3-2',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Floris',
    opdracht: 'W2D3-3',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Floris',
    opdracht: 'W2D4-1',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Floris',
    opdracht: 'W2D4-2',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Floris',
    opdracht: 'W2D4-3',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Floris',
    opdracht: 'W2D5',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Floris',
    opdracht: 'W3D1-1',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Floris',
    opdracht: 'W3D1-2',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Floris',
    opdracht: 'W3D1-3',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Floris',
    opdracht: 'W3D1-4',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Floris',
    opdracht: 'W3D2-1',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Floris',
    opdracht: 'W3D2-2',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Floris',
    opdracht: 'W3D2-3',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Floris',
    opdracht: 'W3D3-1',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Floris',
    opdracht: 'W3D3-2',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Floris',
    opdracht: 'W3D3-3',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Floris',
    opdracht: 'W3D3-4',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Floris',
    opdracht: 'W3D4-1',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Floris',
    opdracht: 'W3D4-2',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Floris',
    opdracht: 'W3D5',
    moeilijkheid: 4,
    plezier: 2,
  },
  {
    student: 'Floris',
    opdracht: 'W4D2-1',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Floris',
    opdracht: 'W4D2-2',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Floris',
    opdracht: 'W4D2-3',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Floris',
    opdracht: 'W4D2-4',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Floris',
    opdracht: 'W4D3-1',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Floris',
    opdracht: 'W4D3-2',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Floris',
    opdracht: 'W4D3-3',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Floris',
    opdracht: 'W4D3-4',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Floris',
    opdracht: 'W4D3-5',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Floris',
    opdracht: 'W4D3',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Floris',
    opdracht: 'W5D4-1',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Floris',
    opdracht: 'W5D5',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Floris',
    opdracht: 'W6D1-1',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Floris',
    opdracht: 'W6D2-1',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Floris',
    opdracht: 'W6D2',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Hector',
    opdracht: 'W4D2',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Hector',
    opdracht: 'W1D1-1',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Hector',
    opdracht: 'W1D2-1',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Hector',
    opdracht: 'W1D2-2',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Hector',
    opdracht: 'W1D2-3',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Hector',
    opdracht: 'W1D2-4',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Hector',
    opdracht: 'W1D2-5',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Hector',
    opdracht: 'W1D3-1',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Hector',
    opdracht: 'W1D3-2',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Hector',
    opdracht: 'W1D3-4',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Hector',
    opdracht: 'W1D3-5',
    moeilijkheid: 4,
    plezier: 2,
  },
  {
    student: 'Hector',
    opdracht: 'W1D3',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Hector',
    opdracht: 'W1D4-1',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Hector',
    opdracht: 'W1D4',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Hector',
    opdracht: 'W1D5',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Hector',
    opdracht: 'W2D1-1',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Hector',
    opdracht: 'W2D1-2',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Hector',
    opdracht: 'W2D2-1',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Hector',
    opdracht: 'W2D2-2',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Hector',
    opdracht: 'W2D2-3',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Hector',
    opdracht: 'W2D3-1',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Hector',
    opdracht: 'W2D3-2',
    moeilijkheid: 4,
    plezier: 2,
  },
  {
    student: 'Hector',
    opdracht: 'W2D3-3',
    moeilijkheid: 4,
    plezier: 2,
  },
  {
    student: 'Hector',
    opdracht: 'W2D4-1',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Hector',
    opdracht: 'W2D4-2',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Hector',
    opdracht: 'W2D4-3',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Hector',
    opdracht: 'W2D5',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Hector',
    opdracht: 'W3D1-1',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Hector',
    opdracht: 'W3D1-2',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Hector',
    opdracht: 'W3D1-3',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Hector',
    opdracht: 'W3D1-4',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Hector',
    opdracht: 'W3D2-1',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Hector',
    opdracht: 'W3D2-2',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Hector',
    opdracht: 'W3D2-3',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Hector',
    opdracht: 'W3D3-1',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Hector',
    opdracht: 'W3D3-2',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Hector',
    opdracht: 'W3D3-3',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Hector',
    opdracht: 'W3D3-4',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Hector',
    opdracht: 'W3D4-1',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Hector',
    opdracht: 'W3D4-2',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Hector',
    opdracht: 'W3D5',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Hector',
    opdracht: 'W4D2-1',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Hector',
    opdracht: 'W4D2-2',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Hector',
    opdracht: 'W4D2-3',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Hector',
    opdracht: 'W4D2-4',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Hector',
    opdracht: 'W4D3-1',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Hector',
    opdracht: 'W4D3-2',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Hector',
    opdracht: 'W4D3-3',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Hector',
    opdracht: 'W4D3-4',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Hector',
    opdracht: 'W4D3-5',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Hector',
    opdracht: 'W4D3',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Hector',
    opdracht: 'W5D4-1',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Hector',
    opdracht: 'W5D5',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Hector',
    opdracht: 'W6D1-1',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Hector',
    opdracht: 'W6D2-1',
    moeilijkheid: 4,
    plezier: 2,
  },
  {
    student: 'Hector',
    opdracht: 'W6D2',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Martina',
    opdracht: 'W4D2',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Martina',
    opdracht: 'W1D1-1',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Martina',
    opdracht: 'W1D2-1',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Martina',
    opdracht: 'W1D2-2',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Martina',
    opdracht: 'W1D2-3',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Martina',
    opdracht: 'W1D2-4',
    moeilijkheid: 4,
    plezier: 2,
  },
  {
    student: 'Martina',
    opdracht: 'W1D2-5',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Martina',
    opdracht: 'W1D3-1',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Martina',
    opdracht: 'W1D3-2',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Martina',
    opdracht: 'W1D3-4',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Martina',
    opdracht: 'W1D3-5',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Martina',
    opdracht: 'W1D3',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Martina',
    opdracht: 'W1D4-1',
    moeilijkheid: 4,
    plezier: 2,
  },
  {
    student: 'Martina',
    opdracht: 'W1D4',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Martina',
    opdracht: 'W1D5',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Martina',
    opdracht: 'W2D1-1',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Martina',
    opdracht: 'W2D1-2',
    moeilijkheid: 4,
    plezier: 2,
  },
  {
    student: 'Martina',
    opdracht: 'W2D2-1',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Martina',
    opdracht: 'W2D2-2',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Martina',
    opdracht: 'W2D2-3',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Martina',
    opdracht: 'W2D3-1',
    moeilijkheid: 4,
    plezier: 2,
  },
  {
    student: 'Martina',
    opdracht: 'W2D3-2',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Martina',
    opdracht: 'W2D3-3',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Martina',
    opdracht: 'W2D4-1',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Martina',
    opdracht: 'W2D4-2',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Martina',
    opdracht: 'W2D4-3',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Martina',
    opdracht: 'W2D5',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Martina',
    opdracht: 'W3D1-1',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Martina',
    opdracht: 'W3D1-2',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Martina',
    opdracht: 'W3D1-3',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Martina',
    opdracht: 'W3D1-4',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Martina',
    opdracht: 'W3D2-1',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Martina',
    opdracht: 'W3D2-2',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Martina',
    opdracht: 'W3D2-3',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Martina',
    opdracht: 'W3D3-1',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Martina',
    opdracht: 'W3D3-2',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Martina',
    opdracht: 'W3D3-3',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Martina',
    opdracht: 'W3D3-4',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Martina',
    opdracht: 'W3D4-1',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Martina',
    opdracht: 'W3D4-2',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Martina',
    opdracht: 'W3D5',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Martina',
    opdracht: 'W4D2-1',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Martina',
    opdracht: 'W4D2-2',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Martina',
    opdracht: 'W4D2-3',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Martina',
    opdracht: 'W4D2-4',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Martina',
    opdracht: 'W4D3-1',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Martina',
    opdracht: 'W4D3-2',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Martina',
    opdracht: 'W4D3-3',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Martina',
    opdracht: 'W4D3-4',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Martina',
    opdracht: 'W4D3-5',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Martina',
    opdracht: 'W4D3',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Martina',
    opdracht: 'W5D4-1',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Martina',
    opdracht: 'W5D5',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Martina',
    opdracht: 'W6D1-1',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Martina',
    opdracht: 'W6D2-1',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Martina',
    opdracht: 'W6D2',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Maurits',
    opdracht: 'W4D2',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Maurits',
    opdracht: 'W1D1-1',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Maurits',
    opdracht: 'W1D2-1',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Maurits',
    opdracht: 'W1D2-2',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Maurits',
    opdracht: 'W1D2-3',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Maurits',
    opdracht: 'W1D2-4',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Maurits',
    opdracht: 'W1D2-5',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Maurits',
    opdracht: 'W1D3-1',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Maurits',
    opdracht: 'W1D3-2',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Maurits',
    opdracht: 'W1D3-4',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Maurits',
    opdracht: 'W1D3-5',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Maurits',
    opdracht: 'W1D3',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Maurits',
    opdracht: 'W1D4-1',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Maurits',
    opdracht: 'W1D4',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Maurits',
    opdracht: 'W1D5',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Maurits',
    opdracht: 'W2D1-1',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Maurits',
    opdracht: 'W2D1-2',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Maurits',
    opdracht: 'W2D2-1',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Maurits',
    opdracht: 'W2D2-2',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Maurits',
    opdracht: 'W2D2-3',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Maurits',
    opdracht: 'W2D3-1',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Maurits',
    opdracht: 'W2D3-2',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Maurits',
    opdracht: 'W2D3-3',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Maurits',
    opdracht: 'W2D4-1',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Maurits',
    opdracht: 'W2D4-2',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Maurits',
    opdracht: 'W2D4-3',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Maurits',
    opdracht: 'W2D5',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Maurits',
    opdracht: 'W3D1-1',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Maurits',
    opdracht: 'W3D1-2',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Maurits',
    opdracht: 'W3D1-3',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Maurits',
    opdracht: 'W3D1-4',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Maurits',
    opdracht: 'W3D2-1',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Maurits',
    opdracht: 'W3D2-2',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Maurits',
    opdracht: 'W3D2-3',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Maurits',
    opdracht: 'W3D3-1',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Maurits',
    opdracht: 'W3D3-2',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Maurits',
    opdracht: 'W3D3-3',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Maurits',
    opdracht: 'W3D3-4',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Maurits',
    opdracht: 'W3D4-1',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Maurits',
    opdracht: 'W3D4-2',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Maurits',
    opdracht: 'W3D5',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Maurits',
    opdracht: 'W4D2-1',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Maurits',
    opdracht: 'W4D2-2',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Maurits',
    opdracht: 'W4D2-3',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Maurits',
    opdracht: 'W4D2-4',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Maurits',
    opdracht: 'W4D3-1',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Maurits',
    opdracht: 'W4D3-2',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Maurits',
    opdracht: 'W4D3-3',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Maurits',
    opdracht: 'W4D3-4',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Maurits',
    opdracht: 'W4D3-5',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Maurits',
    opdracht: 'W4D3',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Maurits',
    opdracht: 'W5D4-1',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Maurits',
    opdracht: 'W5D5',
    moeilijkheid: 4,
    plezier: 2,
  },
  {
    student: 'Maurits',
    opdracht: 'W6D1-1',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Maurits',
    opdracht: 'W6D2-1',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Maurits',
    opdracht: 'W6D2',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Rahima',
    opdracht: 'W4D2',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Rahima',
    opdracht: 'W1D1-1',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Rahima',
    opdracht: 'W1D2-1',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Rahima',
    opdracht: 'W1D2-2',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Rahima',
    opdracht: 'W1D2-3',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Rahima',
    opdracht: 'W1D2-4',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Rahima',
    opdracht: 'W1D2-5',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Rahima',
    opdracht: 'W1D3-1',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Rahima',
    opdracht: 'W1D3-2',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Rahima',
    opdracht: 'W1D3-4',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Rahima',
    opdracht: 'W1D3-5',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Rahima',
    opdracht: 'W1D3',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Rahima',
    opdracht: 'W1D4-1',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Rahima',
    opdracht: 'W1D4',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Rahima',
    opdracht: 'W1D5',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Rahima',
    opdracht: 'W2D1-1',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Rahima',
    opdracht: 'W2D1-2',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Rahima',
    opdracht: 'W2D2-1',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Rahima',
    opdracht: 'W2D2-2',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Rahima',
    opdracht: 'W2D2-3',
    moeilijkheid: 4,
    plezier: 2,
  },
  {
    student: 'Rahima',
    opdracht: 'W2D3-1',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Rahima',
    opdracht: 'W2D3-2',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Rahima',
    opdracht: 'W2D3-3',
    moeilijkheid: 4,
    plezier: 2,
  },
  {
    student: 'Rahima',
    opdracht: 'W2D4-1',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Rahima',
    opdracht: 'W2D4-2',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Rahima',
    opdracht: 'W2D4-3',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Rahima',
    opdracht: 'W2D5',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Rahima',
    opdracht: 'W3D1-1',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Rahima',
    opdracht: 'W3D1-2',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Rahima',
    opdracht: 'W3D1-3',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Rahima',
    opdracht: 'W3D1-4',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Rahima',
    opdracht: 'W3D2-1',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Rahima',
    opdracht: 'W3D2-2',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Rahima',
    opdracht: 'W3D2-3',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Rahima',
    opdracht: 'W3D3-1',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Rahima',
    opdracht: 'W3D3-2',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Rahima',
    opdracht: 'W3D3-3',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Rahima',
    opdracht: 'W3D3-4',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Rahima',
    opdracht: 'W3D4-1',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Rahima',
    opdracht: 'W3D4-2',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Rahima',
    opdracht: 'W3D5',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Rahima',
    opdracht: 'W4D2-1',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Rahima',
    opdracht: 'W4D2-2',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Rahima',
    opdracht: 'W4D2-3',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Rahima',
    opdracht: 'W4D2-4',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Rahima',
    opdracht: 'W4D3-1',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Rahima',
    opdracht: 'W4D3-2',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Rahima',
    opdracht: 'W4D3-3',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Rahima',
    opdracht: 'W4D3-4',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Rahima',
    opdracht: 'W4D3-5',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Rahima',
    opdracht: 'W4D3',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Rahima',
    opdracht: 'W5D4-1',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Rahima',
    opdracht: 'W5D5',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Rahima',
    opdracht: 'W6D1-1',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Rahima',
    opdracht: 'W6D2-1',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Rahima',
    opdracht: 'W6D2',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Sandra',
    opdracht: 'W4D2',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Sandra',
    opdracht: 'W1D1-1',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Sandra',
    opdracht: 'W1D2-1',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Sandra',
    opdracht: 'W1D2-2',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Sandra',
    opdracht: 'W1D2-3',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Sandra',
    opdracht: 'W1D2-4',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Sandra',
    opdracht: 'W1D2-5',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Sandra',
    opdracht: 'W1D3-1',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Sandra',
    opdracht: 'W1D3-2',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Sandra',
    opdracht: 'W1D3-4',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Sandra',
    opdracht: 'W1D3-5',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Sandra',
    opdracht: 'W1D3',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Sandra',
    opdracht: 'W1D4-1',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Sandra',
    opdracht: 'W1D4',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Sandra',
    opdracht: 'W1D5',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Sandra',
    opdracht: 'W2D1-1',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Sandra',
    opdracht: 'W2D1-2',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Sandra',
    opdracht: 'W2D2-1',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Sandra',
    opdracht: 'W2D2-2',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Sandra',
    opdracht: 'W2D2-3',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Sandra',
    opdracht: 'W2D3-1',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Sandra',
    opdracht: 'W2D3-2',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Sandra',
    opdracht: 'W2D3-3',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Sandra',
    opdracht: 'W2D4-1',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Sandra',
    opdracht: 'W2D4-2',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Sandra',
    opdracht: 'W2D4-3',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Sandra',
    opdracht: 'W2D5',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Sandra',
    opdracht: 'W3D1-1',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Sandra',
    opdracht: 'W3D1-2',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Sandra',
    opdracht: 'W3D1-3',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Sandra',
    opdracht: 'W3D1-4',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Sandra',
    opdracht: 'W3D2-1',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Sandra',
    opdracht: 'W3D2-2',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Sandra',
    opdracht: 'W3D2-3',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Sandra',
    opdracht: 'W3D3-1',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Sandra',
    opdracht: 'W3D3-2',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Sandra',
    opdracht: 'W3D3-3',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Sandra',
    opdracht: 'W3D3-4',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Sandra',
    opdracht: 'W3D4-1',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Sandra',
    opdracht: 'W3D4-2',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Sandra',
    opdracht: 'W3D5',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Sandra',
    opdracht: 'W4D2-1',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Sandra',
    opdracht: 'W4D2-2',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Sandra',
    opdracht: 'W4D2-3',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Sandra',
    opdracht: 'W4D2-4',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Sandra',
    opdracht: 'W4D3-1',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Sandra',
    opdracht: 'W4D3-2',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Sandra',
    opdracht: 'W4D3-3',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Sandra',
    opdracht: 'W4D3-4',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Sandra',
    opdracht: 'W4D3-5',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Sandra',
    opdracht: 'W4D3',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Sandra',
    opdracht: 'W5D4-1',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Sandra',
    opdracht: 'W5D5',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Sandra',
    opdracht: 'W6D1-1',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Sandra',
    opdracht: 'W6D2-1',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Sandra',
    opdracht: 'W6D2',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Wietske',
    opdracht: 'W4D2',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Wietske',
    opdracht: 'W1D1-1',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Wietske',
    opdracht: 'W1D2-1',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Wietske',
    opdracht: 'W1D2-2',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Wietske',
    opdracht: 'W1D2-3',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Wietske',
    opdracht: 'W1D2-4',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Wietske',
    opdracht: 'W1D2-5',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Wietske',
    opdracht: 'W1D3-1',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Wietske',
    opdracht: 'W1D3-2',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Wietske',
    opdracht: 'W1D3-4',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Wietske',
    opdracht: 'W1D3-5',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Wietske',
    opdracht: 'W1D3',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Wietske',
    opdracht: 'W1D4-1',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Wietske',
    opdracht: 'W1D4',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Wietske',
    opdracht: 'W1D5',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Wietske',
    opdracht: 'W2D1-1',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Wietske',
    opdracht: 'W2D1-2',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Wietske',
    opdracht: 'W2D2-1',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Wietske',
    opdracht: 'W2D2-2',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Wietske',
    opdracht: 'W2D2-3',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Wietske',
    opdracht: 'W2D3-1',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Wietske',
    opdracht: 'W2D3-2',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Wietske',
    opdracht: 'W2D3-3',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Wietske',
    opdracht: 'W2D4-1',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Wietske',
    opdracht: 'W2D4-2',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Wietske',
    opdracht: 'W2D4-3',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Wietske',
    opdracht: 'W2D5',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Wietske',
    opdracht: 'W3D1-1',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Wietske',
    opdracht: 'W3D1-2',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Wietske',
    opdracht: 'W3D1-3',
    moeilijkheid: 4,
    plezier: 2,
  },
  {
    student: 'Wietske',
    opdracht: 'W3D1-4',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Wietske',
    opdracht: 'W3D2-1',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Wietske',
    opdracht: 'W3D2-2',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Wietske',
    opdracht: 'W3D2-3',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Wietske',
    opdracht: 'W3D3-1',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Wietske',
    opdracht: 'W3D3-2',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Wietske',
    opdracht: 'W3D3-3',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Wietske',
    opdracht: 'W3D3-4',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Wietske',
    opdracht: 'W3D4-1',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Wietske',
    opdracht: 'W3D4-2',
    moeilijkheid: 4,
    plezier: 2,
  },
  {
    student: 'Wietske',
    opdracht: 'W3D5',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Wietske',
    opdracht: 'W4D2-1',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Wietske',
    opdracht: 'W4D2-2',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Wietske',
    opdracht: 'W4D2-3',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Wietske',
    opdracht: 'W4D2-4',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Wietske',
    opdracht: 'W4D3-1',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Wietske',
    opdracht: 'W4D3-2',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Wietske',
    opdracht: 'W4D3-3',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Wietske',
    opdracht: 'W4D3-4',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Wietske',
    opdracht: 'W4D3-5',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Wietske',
    opdracht: 'W4D3',
    moeilijkheid: 4,
    plezier: 2,
  },
  {
    student: 'Wietske',
    opdracht: 'W5D4-1',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Wietske',
    opdracht: 'W5D5',
    moeilijkheid: 4,
    plezier: 2,
  },
  {
    student: 'Wietske',
    opdracht: 'W6D1-1',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Wietske',
    opdracht: 'W6D2-1',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Wietske',
    opdracht: 'W6D2',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Storm',
    opdracht: 'W4D2',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Storm',
    opdracht: 'W1D1-1',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Storm',
    opdracht: 'W1D2-1',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Storm',
    opdracht: 'W1D2-2',
    moeilijkheid: 1,
    plezier: 3,
  },
  {
    student: 'Storm',
    opdracht: 'W1D2-3',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Storm',
    opdracht: 'W1D2-4',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Storm',
    opdracht: 'W1D2-5',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Storm',
    opdracht: 'W1D3-1',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Storm',
    opdracht: 'W1D3-2',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Storm',
    opdracht: 'W1D3-4',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Storm',
    opdracht: 'W1D3-5',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Storm',
    opdracht: 'W1D3',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Storm',
    opdracht: 'W1D4-1',
    moeilijkheid: 4,
    plezier: 2,
  },
  {
    student: 'Storm',
    opdracht: 'W1D4',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Storm',
    opdracht: 'W1D5',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Storm',
    opdracht: 'W2D1-1',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Storm',
    opdracht: 'W2D1-2',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Storm',
    opdracht: 'W2D2-1',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Storm',
    opdracht: 'W2D2-2',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Storm',
    opdracht: 'W2D2-3',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Storm',
    opdracht: 'W2D3-1',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Storm',
    opdracht: 'W2D3-2',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Storm',
    opdracht: 'W2D3-3',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Storm',
    opdracht: 'W2D4-1',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Storm',
    opdracht: 'W2D4-2',
    moeilijkheid: 4,
    plezier: 3,
  },
  {
    student: 'Storm',
    opdracht: 'W2D4-3',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Storm',
    opdracht: 'W2D5',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Storm',
    opdracht: 'W3D1-1',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Storm',
    opdracht: 'W3D1-2',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Storm',
    opdracht: 'W3D1-3',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Storm',
    opdracht: 'W3D1-4',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Storm',
    opdracht: 'W3D2-1',
    moeilijkheid: 1,
    plezier: 4,
  },
  {
    student: 'Storm',
    opdracht: 'W3D2-2',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Storm',
    opdracht: 'W3D2-3',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Storm',
    opdracht: 'W3D3-1',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Storm',
    opdracht: 'W3D3-2',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Storm',
    opdracht: 'W3D3-3',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Storm',
    opdracht: 'W3D3-4',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Storm',
    opdracht: 'W3D4-1',
    moeilijkheid: 2,
    plezier: 4,
  },
  {
    student: 'Storm',
    opdracht: 'W3D4-2',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Storm',
    opdracht: 'W3D5',
    moeilijkheid: 3,
    plezier: 2,
  },
  {
    student: 'Storm',
    opdracht: 'W4D2-1',
    moeilijkheid: 2,
    plezier: 1,
  },
  {
    student: 'Storm',
    opdracht: 'W4D2-2',
    moeilijkheid: 3,
    plezier: 3,
  },
  {
    student: 'Storm',
    opdracht: 'W4D2-3',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Storm',
    opdracht: 'W4D2-4',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Storm',
    opdracht: 'W4D3-1',
    moeilijkheid: 3,
    plezier: 4,
  },
  {
    student: 'Storm',
    opdracht: 'W4D3-2',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Storm',
    opdracht: 'W4D3-3',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Storm',
    opdracht: 'W4D3-4',
    moeilijkheid: 3,
    plezier: 1,
  },
  {
    student: 'Storm',
    opdracht: 'W4D3-5',
    moeilijkheid: 2,
    plezier: 3,
  },
  {
    student: 'Storm',
    opdracht: 'W4D3',
    moeilijkheid: 4,
    plezier: 1,
  },
  {
    student: 'Storm',
    opdracht: 'W5D4-1',
    moeilijkheid: 2,
    plezier: 2,
  },
  {
    student: 'Storm',
    opdracht: 'W5D5',
    moeilijkheid: 1,
    plezier: 2,
  },
  {
    student: 'Storm',
    opdracht: 'W6D1-1',
    moeilijkheid: 4,
    plezier: 4,
  },
  {
    student: 'Storm',
    opdracht: 'W6D2-1',
    moeilijkheid: 1,
    plezier: 1,
  },
  {
    student: 'Storm',
    opdracht: 'W6D2',
    moeilijkheid: 3,
    plezier: 3,
  },
];

const Students = [...new Set(StudentData.map(i => i.student))];

// calculate average rating for each assignment:
let studentReviews = StudentData;
let calcDifficultyAverage = (data, opdracht) => {
  const filterOpdracht = data.filter(item => item.opdracht === opdracht);
  const opdrachtTotal = filterOpdracht.length;

  const totalMoeilijkheid = filterOpdracht.reduce(
    (sum, current) => sum + current.moeilijkheid,
    0
  );
  return totalMoeilijkheid / opdrachtTotal;
};

let calcEnjoyAverage = (data, opdracht) => {
  const filterOpdracht = data.filter(item => item.opdracht === opdracht);
  const opdrachtTotal = filterOpdracht.length;
  const totalEnjoy = filterOpdracht.reduce(
    (sum, current) => sum + current.plezier,
    0
  );
  return totalEnjoy / opdrachtTotal;
};

const getAverageScores = (data, opdracht) => {
  const assignment = opdracht;
  const averageDifficultyScore = calcDifficultyAverage(data, opdracht);
  const averageEnjoyScore = calcEnjoyAverage(data, opdracht);
  const newObject = {
    opdracht: assignment,
    moeilijkheid: averageDifficultyScore,
    plezier: averageEnjoyScore,
  };
  return newObject;
};

const studentReviewsAverage = studentReviews.map(item =>
  getAverageScores(studentReviews, item.opdracht)
);

let ShowAvgScores = studentReviewsAverage.slice(0, 56);

export default { ShowAvgScores, StudentData, Students };
